- onelogin-saml-sso/php/functions.php
saml_sls was not calling exit() after wp_redirect() which caused
execution to continue, and subsequent calls to single login
could cause the user to remain logged in.
Fixes: https://wordpress.org/support/topic/clicking-sign-out-doesnt-invalidate-session
> call exit after logout

- onelogin-saml-sso/php/functions.php
This was made to be an unobtrusive way to implement custom roles so that no one had to change the plugin directly and would have their changes reverted every update.
> Uncomment out filter based custom role code.

- onelogin-saml-sso/php/configuration.php
Minor typo correction.
Signed-off-by: Alex Eiser <alex.eiser@collectivehealth.com>
> Correct typo in documentation

- onelogin-saml-sso/php/settings.php
there's no guarantee that wp-content will be off the root directory or that it will even be named `wp-content` or that the path to the plugins directory even sits inside `wp-content`. Better to use WordPress's built-in functions to determine the correct path.
> use WP to determine wp-content path

- onelogin-saml-sso/php/settings.php
With #29, the URL was updated to use `plugins_url()` for alternative acs, but is still accidentally concatenated with `site_url()`, giving an invalid URL like `http://example.comhttp://example.com/wp-content/...`
While I was here, I also changed the site URL call to just use `wp_login_url()`
> Avoid double site URL concatenation

- onelogin-saml-sso/php/configuration.php
The php-saml/xmlseclibs ([https://github.com/onelogin/php-saml/blob/master/extlib/xmlseclibs/xmlseclibs.php](https://github.com/onelogin/php-saml/blob/master/extlib/xmlseclibs/xmlseclibs.php)) expects a URL as a parameter for signature & digest algorithm.
The keys sent are not in the correct format, the pull-request allows to correct this.
> Fix key value for signature & digest algorithm

- onelogin-saml-sso/php/functions.php
When `onelogin_saml_forcelogin` is enabled, [WP-CLI](http://wp-cli.org/) will silently exit.
> Allow WP-CLI to work

- onelogin-saml-sso/php/functions.php
As the SSO plugin should be the autoritative login solution running on a site, it should enforce redirection in case it's needed.
This commit replaced `return false;` with `exit;` in `saml_lostpassword` and `saml_user_register` functions. That way, we make sure the redirection happens early and would be the very last action of the HTTP request in WordPress.
See https://developer.wordpress.org/reference/functions/wp_redirect/
> Always exit after wp_redirect

- onelogin-saml-sso/php/compatibility.php
- onelogin-saml-sso/php/configuration.php
- onelogin-saml-sso/php/functions.php
- onelogin-saml-sso/php/validate.php
As the plugin is being used on the WordPress.com VIP platform, we have noticed some minor escaping issues while doing code review of the plugin. This commit is fixing the escaping related issues in order to make sure we don't have to patch the plugin for our clients on the platform.
*In some cases, there is `esc_html` used for escaping HTML attribute (`esc_attr` should be used instead).
*In other cases, an escaping function is missing altogether.
*Not all URLs are being properly escaped. This commit is adding `esc_url` everywhere, where valid URL is expected.
This PR also contains one PHPCS related comment - `// Override ok.` which assures PHPCS that the override of a global variable is okay.
> Fix wrong and missing late escaping.

- onelogin-saml-sso/php/functions.php
This commit is replacing `parse_url` by `wp_parse_url` function, which is a WordPress wrapper for PHP inconsistencies. While working on related code, this PR is cleaning up the code.
* There is no need to parse and obtain whole url. Passing PHP_URL_QUERY to `wp_parse_url` function gets us just the bit we need.
* There is no need to define the `$result` param prior calling `parse_str` function.
* variable `$target` is not being used. Thus has been removed.
> Refactor query string parsing for RelayState redirect

- onelogin-saml-sso/onelogin_saml.php
- onelogin-saml-sso/php/functions.php
Storing cookie names in constants allows overriding the cookie names.
Eg.: on the VIP Go platform (part of the WordPress.com VIP offering), we do automatically whitelist cookies prefixed with `wordpress_` in our Varnish configuration. Being able to change cookie names allows us to not introduce new Varnish and Nginx rules for this plugin specifically.
Also, actually, for clients using the plugin on our platform, we had to modify the names which makes it's updates more involved.
> Use constants for storing cookie names

- onelogin-saml-sso/php/configuration.php
- onelogin-saml-sso/php/functions.php
If an IDP login / Authentication has a Remember Me option (such as a checkbox), that value can be set as a SAML Attribute and mapped in WordPress, to utilize WordPress's default 'Remember Me' function.
This effectively logs a person into WordPress for 14 days compared to the session cookie of 24 hours or browser close.
> Add Remember Me option

- onelogin-saml-sso/php/functions.php
…ordPress action
This was merged in previously but someone removed it (see https://github.com/onelogin/wordpress-saml/commit/e857c7735e828f58f9c0dea788ae4ea85390514a#diff-c2929a37119c3b2eafb6e50b579eaefb)
please remerge and release on wordpress.org
Thanks!
> add back code that was accidentally removed?

- onelogin-saml-sso/php/functions.php
Based on the way `is_user_member_of_blog(...)` works...
https://core.trac.wordpress.org/browser/tags/4.9.8/src/wp-includes/user.php#L703
... providing an undefined variable will work the same as not providing anything for
the optional `$blog_id` variable, so I'm simply removing it from this function call.
Fixes #67
> Stop using `$blog_id` before it's defined

- onelogin-saml-sso/php/configuration.php
This fixes a small spelling error on the configuration page.
> Spelling fix for "Errors and Warnigs" on config page

- onelogin-saml-sso/onelogin_saml.php
- onelogin-saml-sso/php/configuration.php
- onelogin-saml-sso/php/network.php
- onelogin-saml-sso/php/network_saml_enabler.php
- onelogin-saml-sso/php/network_saml_injection.php
Now on the Network interface, if the SAML plugin is active, will appear the following menu:
At the "Settings" the user will be able to set "network" settings that later can be injected on the SAML settings of the different sites
("Inject SAML Settings in sites" section).  When injecting, previous SAML settings of the site will be overridden.
At the "Enable/Disable SAML on sites" the admin can review hat sites have the SAML feature enabled and change it status on the different sites directly on this global panel.
> Multisite improvement: Be able to manage multiple SAML settings on different sites.

- onelogin-saml-sso/php/configuration.php
The global `$_POST['global_jit']` is being assigned the value of `on` in the conditional when the intention is to compare its value instead. This PR changes the assignment operator (`=`) to a comparison operator (`===`).
> Fix variable assignment during conditional check

- onelogin-saml-sso/php/validate.php
Not all hosting providers allow users to delete plugins, so this check might be disabled.
> Swap to `manage_options` for the cap check on the validate page.

- onelogin-saml-sso/php/functions.php
bug: Fixed issue with `wp_login` action missing `$user` object, also be sure a user is returned prior to firing `do_action` 
chore: minor WPCS code formatting updates.
resolves: #106
> bug: Fixed issue with wp_login action missing $user object

- onelogin-saml-sso/php/functions.php
Detect whether WPS Hide Plugin is installed and enabled. If so, make sure the hidden URL is used instead of wp-login.php in SAML Login URL. If this is not the case, the RelayState parameter is not set properly.
> Add Support for WPS Hide Login

- onelogin-saml-sso/php/settings.php
Small PR to use `add_query_arg` instead of manual string concatenation. Provides slightly better reliability in case `wp_login_url` is filtered to include a default query string for some reason.
> Use add_query_arg to better adjust login URLs
